# Generated by Django 4.0.3 on 2022-03-31 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='department',
            field=models.CharField(help_text='Enter a Department (e.g. IT)', max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Make must be greater than 1 character')]),
        ),
    ]
