# Generated by Django 4.0.3 on 2022-03-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
    ]
