# Generated by Django 4.0.3 on 2022-03-31 10:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_alter_department_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter a name of teacher', max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Make must be greater than 1 character')])),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.department')),
            ],
        ),
    ]
