# Generated by Django 4.0.3 on 2022-03-31 10:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(help_text='Enter a name of Teacher', max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Make must be greater than 1 character')]),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter a name of Subject (e.g. DSA)', max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Make must be greater than 1 character')])),
                ('department', models.ForeignKey(help_text='Department under which this subject comes', on_delete=django.db.models.deletion.CASCADE, to='feed.department')),
                ('teacher', models.ForeignKey(help_text='Teacher teaching this subject', on_delete=django.db.models.deletion.CASCADE, to='feed.teacher')),
            ],
        ),
    ]
