# Generated by Django 4.0.3 on 2022-03-31 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_alter_teacher_name_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(help_text='Teacher teaching this subject', null=True, on_delete=django.db.models.deletion.SET_NULL, to='feed.teacher'),
        ),
    ]
