# Generated by Django 4.0.3 on 2022-05-29 03:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_alter_subject_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tfeed',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('branch', models.CharField(help_text='Enter a Department (e.g. IT)', max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Make must be greater than 1 character')])),
                ('sem', models.IntegerField(help_text='Sem of student eg.1')),
                ('interact', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('softSkill', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('notes', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('ans', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('pInteract', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('quality', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('extra', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('assignment', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('interrupt', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('mst', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('lecture', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('mooc', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('virtualLab', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('curriculum', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('topic', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('dep', models.ForeignKey(help_text='Department under which this subject comes', null=True, on_delete=django.db.models.deletion.SET_NULL, to='feed.department')),
                ('sub', models.ForeignKey(help_text='Department under which this subject comes', null=True, on_delete=django.db.models.deletion.SET_NULL, to='feed.subject')),
                ('teach', models.ForeignKey(help_text='Teacher teaching this subject', null=True, on_delete=django.db.models.deletion.SET_NULL, to='feed.teacher')),
            ],
        ),
    ]
