# Generated by Django 4.0.3 on 2022-05-29 03:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_tfeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tfeed',
            name='ans',
            field=models.IntegerField(help_text='1-10', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tfeed',
            name='assignment',
            field=models.IntegerField(help_text='1-10', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tfeed',
            name='curriculum',
            field=models.IntegerField(help_text='1-10', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tfeed',
            name='extra',
            field=models.IntegerField(help_text='1-10', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tfeed',
            name='interact',
            field=models.IntegerField(help_text='1-10', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tfeed',
            name='interrupt',
            field=models.IntegerField(help_text='1-10', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tfeed',
            name='lecture',
            field=models.IntegerField(help_text='1-10', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tfeed',
            name='mooc',
            field=models.IntegerField(help_text='1-10', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tfeed',
            name='mst',
            field=models.IntegerField(help_text='1-10', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tfeed',
            name='notes',
            field=models.IntegerField(help_text='1-10', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tfeed',
            name='pInteract',
            field=models.IntegerField(help_text='1-10', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tfeed',
            name='quality',
            field=models.IntegerField(help_text='1-10', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tfeed',
            name='softSkill',
            field=models.IntegerField(help_text='1-10', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tfeed',
            name='topic',
            field=models.IntegerField(help_text='1-10', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tfeed',
            name='virtualLab',
            field=models.IntegerField(help_text='1-10', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
