# Generated by Django 4.0.3 on 2022-05-29 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_alter_tfeed_ans_alter_tfeed_assignment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tfeed',
            old_name='teach',
            new_name='teacher',
        ),
    ]
