# Generated by Django 4.0.3 on 2022-05-29 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_rename_teach_tfeed_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tfeed',
            old_name='dep',
            new_name='depTeach',
        ),
        migrations.RenameField(
            model_name='tfeed',
            old_name='sub',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='tfeed',
            old_name='teacher',
            new_name='teacherName',
        ),
    ]
