# Generated by Django 4.0.3 on 2022-05-29 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_rename_dep_tfeed_depteach_rename_sub_tfeed_subject_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tfeed',
            new_name='Feed',
        ),
    ]
