# Generated by Django 4.0.3 on 2022-05-31 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_rename_tfeed_feed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='depTeach',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='teacherName',
        ),
    ]
