# Generated by Django 4.0.3 on 2022-05-31 04:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0012_feed_depteach'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='teacherName',
            field=models.CharField(help_text='Enter a Department (e.g. IT)', max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(2, 'Make must be greater than 1 character')]),
        ),
    ]
