# Generated by Django 4.0.3 on 2022-05-31 04:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0015_alter_feed_subject_alter_feed_teachername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='depTeach',
            field=models.CharField(help_text='Enter a Department (e.g. IT)', max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Make must be greater than 1 character')]),
        ),
    ]
