# Generated by Django 4.0.3 on 2022-05-31 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0017_alter_feed_subject_alter_feed_teachername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='sem',
            field=models.IntegerField(help_text='Sem of student (e.g. 1'),
        ),
    ]
