# Generated by Django 4.0.3 on 2022-06-06 10:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0020_alter_feed_sem'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='bless',
            field=models.IntegerField(default='0', help_text='1-10', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='feed',
            name='cooperative',
            field=models.IntegerField(default='0', help_text='1-10', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='feed',
            name='helpful',
            field=models.IntegerField(default='0', help_text='1-10', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
