# Generated by Django 4.0.3 on 2022-06-06 10:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0021_feed_bless_feed_cooperative_feed_helpful'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='bless',
            field=models.IntegerField(help_text='1-10', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='feed',
            name='cooperative',
            field=models.IntegerField(help_text='1-10', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='feed',
            name='helpful',
            field=models.IntegerField(help_text='1-10', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
