# Generated by Django 4.0.3 on 2022-06-06 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0022_alter_feed_bless_alter_feed_cooperative_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='bless',
            field=models.IntegerField(help_text='0 / 1', validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='feed',
            name='cooperative',
            field=models.IntegerField(help_text='0 / 1', validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='feed',
            name='helpful',
            field=models.IntegerField(help_text='0 / 1', validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
    ]
